language: node_js
node_js:
  - 12
  - node

before_install:
  - npm i -g npm@6.14.4

cache: npm
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
